### ISSUE TITLE
It seems that UserImage cannot receive Byte[], but instead receives a base64-encoded string

### ISSUE THREAD

**Issue by xianyvbang** [jellyfin/jellyfin-sdk-kotlin#1014]
Use code:

```
apiClient.imageApi.postUserImage(
                    data = profile.readBytes().toFileInfo("image/png")
 )
```

An error of 500 is returned.

The jellyfin server log displays yes:

```
System.FormatException: One of the identified items was in an invalid format.
   at System.Security.Cryptography.ThrowHelper.ThrowBase64FormatException()
   at System.Security.Cryptography.FromBase64Transform.TransformBlock(Byte[] inputBuffer, Int32 inputOffset, Int32 inputCount, Byte[] outputBuffer, Int32 outputOffset)
   at System.Security.Cryptography.CryptoStream.ReadAsyncCore(Memory`1 buffer, CancellationToken cancellationToken, Boolean useAsync)
   at System.Security.Cryptography.CryptoStream.ReadAsyncInternal(Memory`1 buffer, CancellationToken cancellationToken)
   at System.Security.Cryptography.CryptoStream.CopyToAsyncInternal(Stream destination, Int32 bufferSize, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ImageSaver.SaveImageToLocation(Stream source, String path, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ImageSaver.SaveImageToLocation(Stream source, String path, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ImageSaver.SaveImageToLocation(Stream source, String path, String retryPath, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ImageSaver.SaveImage(Stream source, String path)
   at Jellyfin.Api.Controllers.ImageController.PostUserImage(Nullable`1 userId)
   at Jellyfin.Api.Controllers.ImageController.PostUserImage(Nullable`1 userId)
   at lambda_method1203(Closure, Object)
```
FromBase64Transform is a method for restoring some data from Base64 encoding, as indicated by the object name.So apiClient. ImageApi. PostUserImage method can't upload a Byte [], but rather a Base64 encoded string

**Comment by nielsvanvelzen** [comment]
Correct, most of the image upload APIs require the body to be base64 encoded. That is up to the user of the SDK to do.

**Comment by xianyvbang** [comment]
> Correct, most of the image upload APIs require the body to be base64 encoded. That is up to the user of the SDK to do.
But the FileInfo object has two properties, Byte[] and String, and I can't find any other ImageApi.postUserImage method

**Comment by nielsvanvelzen** [comment]
https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.io.encoding/-base64/

so you would do something like:

```kotlin
apiClient.imageApi.postUserImage(
  data = FileInfo(
    mediaType = "image/png",
    content = Base64.Default.encodeToByteArray(profile.readBytes())
  )
```

or 

```kotlin
apiClient.imageApi.postUserImage(
  data = Base64.Default.encodeToByteArray(profile.readBytes()).toFileInfo("image/png")
)
```

**Comment by xianyvbang** [comment]
> https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.io.encoding/-base64/
> 
> 因此你可以这样做：
> 
> ```kotlin
> apiClient.imageApi.postUserImage(
>   data = FileInfo(
>     mediaType = "image/png",
>     content = Base64.Default.encodeToByteArray(profile.readBytes())
>   )
> ```
> 
> 或者
> 
> ```kotlin
> apiClient.imageApi.postUserImage(
>   data = Base64.Default.encodeToByteArray(profile.readBytes()).toFileInfo("image/png")
> )
> ```

I thought he could only pass a base64 encoded string, but that's still possible. Thank you very much indeed
